namespace SysBot.Pokemon
{
    /// <summary>
    /// Mark Indices
    /// </summary>
    public enum Marks : int
    {
        ChampionKalos = 0,
        ChampionG3 = 1,
        ChampionSinnoh = 2,
        BestFriends = 3,
        Training = 4,
        BattlerSkillful = 5,
        BattlerExpert = 6,
        Effort = 7,
        Alert = 8,
        Shock = 9,
        Downcast = 10,
        Careless = 11,
        Relax = 12,
        Snooze = 13,
        Smile = 14,
        Gorgeous = 15,
        Royal = 16,
        GorgeousRoyal = 17,
        Artist = 18,
        Footprint = 19,
        Record = 20,
        Legend = 21,
        Country = 22,
        National = 23,
        Earth = 24,
        World = 25,
        Classic = 26,
        Premier = 27,
        Event = 28,
        Birthday = 29,
        Special = 30,
        Souvenir = 31,
        Wishing = 32,
        ChampionBattle = 33,
        ChampionRegional = 34,
        ChampionNational = 35,
        ChampionWorld = 36,
        CountMemoryContest = 37,
        CountMemoryBattle = 38,
        ChampionG6Hoenn = 39,
        ContestStar = 40,
        MasterCoolness = 41,
        MasterBeauty = 42,
        MasterCuteness = 43,
        MasterCleverness = 44,
        MasterToughness = 45,
        ChampionAlola = 46,
        BattleRoyale = 47,
        BattleTreeGreat = 48,
        BattleTreeMaster = 49,
        ChampionGalar = 50,
        TowerMaster = 51,
        MasterRank = 52,

        MarkLunchtime = 54,
        MarkSleepyTime = 55,
        MarkDusk = 56,
        MarkDawn = 57,
        MarkCloudy = 58,
        MarkRainy = 59,
        MarkStormy = 60,
        MarkSnowy = 61,
        MarkBlizzard = 62,
        MarkDry = 63,
        MarkSandstorm = 64,
        MarkMisty = 65,
        MarkDestiny = 66,
        MarkFishing = 67,
        MarkCurry = 68,
        MarkUncommon = 69,
        MarkRare = 70,
        MarkRowdy = 71,
        MarkAbsentMinded = 72,
        MarkJittery = 73,
        MarkExcited = 74,
        MarkCharismatic = 75,
        MarkCalmness = 76,
        MarkIntense = 77,
        MarkZonedOut = 78,
        MarkJoyful = 79,
        MarkAngry = 80,
        MarkSmiley = 81,
        MarkTeary = 82,
        MarkUpbeat = 83,
        MarkPeeved = 84,
        MarkIntellectual = 85,
        MarkFerocious = 86,
        MarkCrafty = 87,
        MarkScowling = 88,
        MarkKindly = 89,
        MarkFlustered = 90,
        MarkPumpedUp = 91,
        MarkZeroEnergy = 92,
        MarkPrideful = 93,
        MarkUnsure = 94,
        MarkHumble = 95,
        MarkThorny = 96,
        MarkVigor = 97,
        MarkSlump = 98,

        Hisui = 100,
        TwinklingStar = 101,

        ChampionPaldea = 103,
        MarkJumbo = 104,
        MarkMini = 105,
        MarkItemfinder = 106,
        MarkPartner = 107,
        MarkGourmand = 108,
        OnceInALifetime = 109,
        MarkAlpha = 110,
        MarkMightiest = 111,
        MarkTitan = 112,

    }
}
